import { GitHubClient } from "./github";
import { PaperclipClient } from "./paperclip";

const SYNC_MARKER_PREFIX = "<!-- paperclip-plan-sync:";

export interface SyncLogger {
  info: (msg: string) => void;
  warn: (msg: string, err?: unknown) => void;
  error: (msg: string, err?: unknown) => void;
}

/**
 * Polls all active Paperclip issues in the project and, for any that have a
 * plan document and a linked GitHub issue, posts the plan as a GitHub comment.
 * Deduplication is done via an HTML marker embedding the plan revision ID so
 * the same revision is never posted twice.
 */
export async function syncContextToGitHub(
  paperclip: PaperclipClient,
  github: GitHubClient,
  companyPrefix: string,
  appBaseUrl: string,
  logger: SyncLogger
): Promise<void> {
  let issues: Awaited<ReturnType<typeof paperclip.getProjectIssues>>;
  try {
    issues = await paperclip.getProjectIssues(["in_progress", "in_review", "done"]);
  } catch (err) {
    logger.error("context-sync: failed to fetch project issues", err);
    return;
  }

  for (const issue of issues) {
    if (!issue.description) continue;
    const ghNumber = paperclip.extractGitHubIssueNumber(issue.description);
    if (!ghNumber) continue;

    try {
      const plan = await paperclip.getIssueDocument(issue.id, "plan");
      if (!plan?.body?.trim()) continue;

      const marker = `${SYNC_MARKER_PREFIX}${plan.revisionId}-->`;
      const alreadySynced = await github.hasComment(ghNumber, marker);
      if (alreadySynced) continue;

      const issueUrl = `${appBaseUrl}/${companyPrefix}/issues/${issue.identifier}`;
      const commentBody = buildPlanComment({ issue, plan, marker, issueUrl });
      await github.addComment(ghNumber, commentBody);
      logger.info(`context-sync: pushed plan for ${issue.identifier} to GitHub #${ghNumber}`);
    } catch (err) {
      logger.warn(`context-sync: skipped ${issue.identifier} (GitHub #${ghNumber})`, err);
    }
  }
}

function buildPlanComment(params: {
  issue: { identifier: string; title: string };
  plan: { body: string; title?: string };
  marker: string;
  issueUrl: string;
}): string {
  const heading = params.plan.title ?? "Plan";
  return [
    params.marker,
    `## 🤖 AI ${heading} — ${params.issue.identifier}`,
    "",
    params.plan.body,
    "",
    "---",
    `*Generated by Paperclip AI · [View Paperclip issue](${params.issueUrl})*`,
  ].join("\n");
}
